version: "3"
services:
  gvm:
    image: mkuchera/gvm11
    ports:
      - "8080:9392"
    environment:
      - USERNAME=${GVM_USER}
      - PASSWORD=${GVM_PASS}
      - HTTPS=${GVM_HTTPS}
      - SSHD=${GVM_SSHD}
      - TZ=${GVM_TZ}
      - SMTP_USER=${MAIL_USER} 
      - SMTP_PASS=${MAIL_PASS}
      - SMTP_DOMAIN=${MAIL_DOMAIN}
      - SMTP_PORT=${MAIL_PORT}
      - REPORT_TAG=${EMAIL_DELTA_TAG}
      - SENT_TAG=${EMAIL_SENT_TAG}
      - DELTA_MAIL_INT=${EMAIL_INT}
    volumes:
    - gvm-data:/data
    - ./scripts:/scripts
    - ./host_info:/host_info
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: >
            /bin/sh -c "/scripts/user_add.sh &&
            ./start.sh"
 
volumes:
  gvm-data:
